[2023-04-29 20:12:47,164] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:12:47] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:12:49,758] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:12:49] "GET /pets/1 HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:13:42,270] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:13:42] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:13:46,668] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:13:46] "GET /pets/1 HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:14:17,610] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:14:17] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:14:20,328] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:14:20] "GET /pets/1 HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:14:26,432] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:14:26] "OPTIONS /pets/1 HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:14:26,706] ERROR log_exception() L1449 Exception on /pets/1 [PUT] - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask_openapi3\scaffold.py", line 273, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Meu Drive\puc\sprint1\back_end\app.py", line 89, in update_pet
    logger.log(f"Alterando o pet: '{pet.nome}'")
TypeError: Logger.log() missing 1 required positional argument: 'msg'
[2023-04-29 20:14:26,725] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:14:26] "[35m[1mPUT /pets/1 HTTP/1.1[0m" 500 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:15:10,054] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:15:10] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:15:17,153] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:15:17] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:15:18,932] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:15:18] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:15:22,642] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:15:22] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:15:42,991] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:15:42] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:15:49,216] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:15:49] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:15:51,533] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:15:51] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:16:08,084] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:16:08] "GET /pets/1 HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:16:14,076] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:16:14] "OPTIONS /pets/1 HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:16:14,344] ERROR log_exception() L1449 Exception on /pets/1 [PUT] - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask_openapi3\scaffold.py", line 273, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Meu Drive\puc\sprint1\back_end\app.py", line 89, in update_pet
    logger.log(f"Alterando o pet: '{pet.nome}'")
TypeError: Logger.log() missing 1 required positional argument: 'msg'
[2023-04-29 20:16:14,352] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:16:14] "[35m[1mPUT /pets/1 HTTP/1.1[0m" 500 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:18:42,569] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:18:42] "GET /pets HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:18:44,367] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:18:44] "GET /pets/1 HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
[2023-04-29 20:18:47,961] INFO _log() L224  127.0.0.1 - - [29/Apr/2023 20:18:47] "OPTIONS /pets/1 HTTP/1.1" 200 - - call_trace=C:\Users\vinia\AppData\Roaming\Python\Python311\site-packages\werkzeug\_internal.py L224 
